### PR TITLE
Feat: Added review system

### PR DESCRIPTION
**Pull request by VishalMinj**
#29 
## Update:
- Update env file
- Minor ui fix
## Added:
- About page for movie review
- Added RBAC based review system
- Added 404 page
- Mild review censorship with better-profanity  

### Note: To access about click on the poster

### CODE REVIEW

**Comment by eleensmathew** [comment]
Can you fix the conflicts and if you can add the review page link in the movie_detail page? Have a look at the models for this. Will give bonus.

**Comment by VishalMinj** [comment]
Done @eleensmathew

**Comment by VishalMinj** [comment]
@eleensmathew you mean somewhere here? Or in the shows page?

image

**Comment by eleensmathew** [comment]
In the movie details page

**Comment by VishalMinj** [comment]
Under genre?

image

**Comment by VishalMinj** [comment]
Hey @eleensmathew please verify the pr

**Pull request merged**
