### PR TITLE
Add movie recommendation Jupyter notebook

### LINKED ISSUE #22: Adding movie Recommendation system
### Expected behavior
Make a KNN-based movie recommendation system. DON'T integrate with the website. The User should input a movie and the system should output n similar movies based on the input. Make a separate Python file or Jupyter notebook (also feel free to make a google colab or kaggle notebook and attach a link to the pr and just add your name into the contributors.md ). Will give bonus points based on accuracy.  Attach screenshots in PR.

Feel free to ask doubts below if facing any confusion.

### PR DESCRIPTION
**Pull request by Aryan10**
## Description

This PR implements a KNN-based movie recommendation system as requested in Issue #22.

## Related Issue

Fixes #22

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

This change is required to fulfill the feature request in Issue #22, which outlines the need for a KNN-based recommendation system. The models implemented allow users to input a movie title and retrieve n similar movies from the dataset.

## How Has This Been Tested?

Tested by running both models with sample movie titles and user ratings. Verified recommendations using popular movies from the dataset. 

## Screenshots (if appropriate):
Movies similar to Toy Story (1995)
image

Movies similar to "Shrek (2001)"
image

Movies similar to "Inception (2010)"
image

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
N/A

### CODE REVIEW

**Comment by Aryan10** [comment]
@eleensmathew Please look into this. The ContriHUB site is down so I can not submit there.

**Comment by eleensmathew** [comment]
Submit this pr through the website. Its running now. If the time alloted is over request assignment again. If you are facing issues then contact abhishek.

**Comment by Aryan10** [comment]
@eleensmathew I have requested assignment again.

**Comment by eleensmathew** [comment]
Great i have accepted it

**Comment by Aryan10** [comment]
@eleensmathew I have sent this PR through ContriHUB site, please look into this.

**Pull request merged**
