### PR TITLE
added star ratings and ui for seat availability

### LINKED ISSUE #8: Add ratings for movie
Please choose your issue template from the following options:

### Expected behavior
Fetch current ratings for a movie from an external API (critics rating). Also, implement a feature where any user without any authentication can rate any movie in movie_list. It would be cool if the ratings were displayed as stars.
image
So under the movie, there must be 
1.a critics rating(fetched from api)
2. user ratings(entered by users on the website)

 
### Current behavior
In http://127.0.0.1:8000/user/movie_list/ Each movie does not have a rating displayed on the movie page or movie_list page.

### PR DESCRIPTION
**Pull request by sakshi-patil-1111**
added the feature of star ratings and ui for seat availability 

## Description

now the show movies page contains the imbd ratings, critic ratings and the rating of the users submitted from the site in star format allowing the user to submit his own ratings through star form . It also shows the number of people who have submitted their ratings. 

UI added to show available and booked seats while booking a ticket
also notifying the user with message seats filling fast

## Related Issue

N/A

Fixes #8 #5 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

N/A

## Screenshots (if appropriate):

Screenshot 2024-10-17 011635

Screenshot 2024-10-17 012319

Screenshot 2024-10-19 200130

Screenshot 2024-10-18 021839

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by eleensmathew** [comment]
Remove all the pycache files

**Comment by sakshi-patil-1111** [comment]
> Remove all the pycache files

done mam

**Comment by eleensmathew** [comment]
image
The drop down option for selecting the seat can be removed and you can implement a way of booking the seats based on the blue selected seats. Also, the message 'seats are filling up fast' may only be displayed when 85% above seats are booked. Please make these changes to the code.

**Comment by sakshi-patil-1111** [comment]
> image The drop down option for selecting the seat can be removed and you can implement a way of booking the seats based on the blue selected seats. Also, the message 'seats are filling up fast' may only be displayed when 85% above seats are booked. Please make these changes to the code.

okay will do,, but it will take some time to implement

**Comment by eleensmathew** [comment]
Take your time

**Comment by sakshi-patil-1111** [comment]
> Take your time

done mam, kindly check

**Comment by sakshi-patil-1111** [comment]
> > Take your time
> 
> done mam, kindly check

Pls check mam

**Comment by eleensmathew** [comment]
Yup I'll check today

**Comment by sakshi-patil-1111** [comment]
Any updates mam?

**Comment by eleensmathew** [comment]
Sorry will check it today

**Pull request merged**
