### PR TITLE
Frontend design modified #7

### PR DESCRIPTION
**Pull request by kirtisrivastava22**
Front end of website modified

## Description

Changes majorily done in stylesheet and html files

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue

Fixes # (issue) Improve Frontend Design

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

Better Frontend 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):
Screenshot 2024-10-10 155902

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x ] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by eleensmathew** [comment]
Can you send screenshots of the new design? Also pls pull the recent changes and resolve the conflicts

**Comment by kirtisrivastava22** [comment]
Screenshot 2024-10-10 155902
Screenshot 2024-10-10 194400

**Comment by kirtisrivastava22** [comment]
Pull the recent changes means to fork again or to commit my recent changes?

**Comment by eleensmathew** [comment]
Pull the commits from my main branch. Also there are some html changes that were made in the screenshots that you added. More pages like movie list and show list have you modified? Also I'll give you bonus for responsiveness.

**Comment by kirtisrivastava22** [comment]
Yes MovieList and showlist page also modified ...But the recent changes are yet to see

**Comment by eleensmathew** [comment]
> Yes MovieList and showlist page also modified ...But the recent changes are yet to see

Recent changed yet to see means? Pls attach screenshots using an example movie and show? The api is omdb.

**Comment by kirtisrivastava22** [comment]
Recent commit changes in html files which were not earlier present when I
forked

**Comment by kirtisrivastava22** [comment]
Pull Request done again https://github.com/ContriHUB/MovieScreen/pull/16#issue-2579392004
@eleensmathew

**Comment by eleensmathew** [comment]
Add screenshots after you have added one movie and one show pls

**Comment by kirtisrivastava22** [comment]
Screenshot 2024-10-10 221258
Screenshot 2024-10-10 234015
Screenshot 2024-10-10 235252

**Comment by kirtisrivastava22** [comment]
With Reference to PR :- https://github.com/ContriHUB/MovieScreen/pull/16#issue-2579392004

**Comment by eleensmathew** [comment]
Great i review it soon

**Comment by kirtisrivastava22** [comment]
Are any more new modifications needed in the frontend design?

**Comment by eleensmathew** [comment]
Hey no need for more changes. I'll check it out locally and i will accept your pr.

**Pull request closed without merging**
