### PR TITLE
feat: Added email message for ticktet confirmation

### PR DESCRIPTION
**Pull request by VishalMinj**
## Updated:
- Adjusted Signup form
- Updated instructions in README.md
## Added:
- Implemented email logic in book_ticket view

### CODE REVIEW

**Comment by VishalMinj** [comment]
Website seems to be down again. What to do about the pr link?

**Comment by eleensmathew** [comment]
Hey is this pr sumbitted through the website? The website is now running.

**Comment by VishalMinj** [comment]
Ain't Showing up in my active issues, seems like someone else has submitted an assignment request. I tried to get reassigned.

**Comment by eleensmathew** [comment]
Its not assigned to anyone. Please contact abhishek through discord

**Comment by VishalMinj** [comment]
Okay

**Comment by VishalMinj** [comment]
I've sent request for issue assignment

**Comment by eleensmathew** [comment]
Great i have accepted it

**Comment by VishalMinj** [comment]
Done!

**Comment by VishalMinj** [comment]
@eleensmathew please merge the pr, or else the request will expire

**Comment by eleensmathew** [comment]
I'll go through it today

**Pull request merged**
